// Mocks generated by Mockito 5.4.6 from annotations
// in delivery_express_mobility_frontend/test/features/deliveries/presentation/bloc/deliveries_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:delivery_express_mobility_frontend/features/deliveries/domain/entities/delivery.dart'
    as _i3;
import 'package:delivery_express_mobility_frontend/features/deliveries/domain/repositories/deliveries_repository.dart'
    as _i2;
import 'package:delivery_express_mobility_frontend/features/deliveries/domain/usecases/deliveries_usecases.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDeliveriesRepository_0 extends _i1.SmartFake
    implements _i2.DeliveriesRepository {
  _FakeDeliveriesRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDelivery_1 extends _i1.SmartFake implements _i3.Delivery {
  _FakeDelivery_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchDeliveriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchDeliveriesUseCase extends _i1.Mock
    implements _i4.FetchDeliveriesUseCase {
  @override
  _i2.DeliveriesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDeliveriesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDeliveriesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DeliveriesRepository);

  @override
  _i5.Future<List<_i3.Delivery>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Delivery>>.value(<_i3.Delivery>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i3.Delivery>>.value(<_i3.Delivery>[]),
      ) as _i5.Future<List<_i3.Delivery>>);
}

/// A class which mocks [GetDeliveryDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDeliveryDetailsUseCase extends _i1.Mock
    implements _i4.GetDeliveryDetailsUseCase {
  @override
  _i2.DeliveriesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDeliveriesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDeliveriesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DeliveriesRepository);

  @override
  _i5.Future<_i3.Delivery> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i5.Future<_i3.Delivery>.value(_FakeDelivery_1(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Delivery>.value(_FakeDelivery_1(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Delivery>);
}

/// A class which mocks [UpdateDeliveryStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateDeliveryStatusUseCase extends _i1.Mock
    implements _i4.UpdateDeliveryStatusUseCase {
  @override
  _i2.DeliveriesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDeliveriesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeDeliveriesRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DeliveriesRepository);

  @override
  _i5.Future<void> call(
    String? id,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            id,
            status,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
